<?php echo $this->doctype(); ?>
<?php 
//$usuario = Zend_Auth::getInstance()->setStorage(new Zend_Auth_Storage_Session('admin'))->getIdentity(); 
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Hotel Management</title>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link href="/css/chosen.css" rel="stylesheet">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/custom.css" rel="stylesheet">
        
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }

            @media (max-width: 980px) {
                /* Enable use of floated navbar text */
                .navbar-text.pull-right {
                    float: none;
                    padding-left: 5px;
                    padding-right: 5px;
                }
            }
        </style>
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="assets/js/html5shiv.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="/ico/favicon.png">

        <script src="/js/jquery.js"></script>
        <script src="/js/maskedinput/src/jquery.maskedinput.js"></script>
        <script src="/js/tinymce/js/tinymce/tinymce.min.js"></script>
<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>-->
        
    </head>

    <body>
        
        <div class="navbar navbar-blue navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="/">Hotel Management</a>
                    <?php if (!empty($usuario)) { ?>
                    <div class="nav-collapse collapse">
                        <div class="navbar-text pull-right btn-sair">
                            <a href="<?php echo $this->url(array('controller' => 'auth', "action" => "logout")); ?>">
                                <img src="/img/ico-sair.png" height="15" width="15" alt="">Sair
                            </a>
                        </div>
                        <!-- btn-sair -->
                        <p class="navbar-text pull-right">
                            Logado como <a href="#" class="navbar-link"><?php echo $usuario->nome; ?></a>
                        </p>
                    </div>
                    <?php } ?>
                    <!-- nav-collapse collapse -->
                </div>
            </div>
        </div>

        <?php // if (!empty($usuario)) { ?>
        <div class="navbar navbar-gray">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <ul class="nav nav-tabs">
                        <?php 
                        if ($this->controller == "Dashboard") {
                            $class = 'class="active"';
                        } else {
                            $class = "";
                        }
                        ?>
                        <li <?php echo $class; ?>><a href="/">Dashboard</a></li>
                        <?php 
                        if ($this->controller == "Hoteis") {
                            $class = 'class="active"';
                        } else {
                            $class = "";
                        }
                        ?>
                        <li <?php echo $class; ?>>
                            <a href="<?php echo $this->url(array('controller' => 'hoteis', "action" => "index"), null, true); ?>">Hoteis</a>
                        </li>
                        <?php 
                        if ($this->controller == "Pre&ccedil;os") {
                            $class = 'class="active"';
                        } else {
                            $class = "";
                        }
                        ?>
                        <li <?php echo $class; ?>>
                            <a href="<?php echo $this->url(array('controller' => 'precos', "action" => "index"), null, true); ?>">Pre&ccedil;os</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <?php // } ?>
        
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span12">
                    <div class="row-fluid show-grid">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
            <hr>
        </div>
        
        <div class="container-fluid">

            <footer>
                <p>&copy; Dialoga - 2014</p>
            </footer>

        </div><!--/.fluid-container-->

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="/js/bootstrap-transition.js"></script>
        <script src="/js/bootstrap-alert.js"></script>
        <script src="/js/bootstrap-modal.js"></script>
        <script src="/js/bootstrap-dropdown.js"></script>
        <script src="/js/bootstrap-scrollspy.js"></script>
        <script src="/js/bootstrap-tab.js"></script>
        <script src="/js/bootstrap-tooltip.js"></script>
        <script src="/js/bootstrap-popover.js"></script>
        <script src="/js/bootstrap-button.js"></script>
        <script src="/js/bootstrap-collapse.js"></script>
        <script src="/js/bootstrap-carousel.js"></script>
        <script src="/js/bootstrap-typeahead.js"></script>
        <script src="/js/chosen.jquery.js"></script>
        <script src="/js/jquery.money.js"></script>
        <script src="/js/datepicker/js/bootstrap-datepicker.js"></script>
        <script src="/js/prism.js"></script>
        
        <script>

//            $('#example').tooltip(options);
            
            var config = {
                '.chosen-select'           : {},
                '.chosen-select-deselect'  : {allow_single_deselect:true},
                '.chosen-select-no-single' : {disable_search_threshold:10},
                '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
                '.chosen-select-width'     : {width:"95%"}
              }
              for (var selector in config) {
                $(selector).chosen(config[selector]);
              }

        </script>
    </body>
</html>
