<div class="title">
    <h1><?php echo $this->controller; ?></h1>
    
    <a class="btn btn btn-info" 
        href="<?php echo $this->url(array('controller' => 'precos', 'action' => 'new')); ?>">
         Novo
    </a>
</div>
<span>
    <br /><br /><br /><br />
    <?php echo $this->messagesFormatter($this->messages); ?>
</span>
<table class="table table-striped">
    <thead>
        <tr>
            <td><strong>Hotel</strong></td>
            <td><strong>Tipo de Cliente</strong></td>
            <td><strong>Dias</strong></td>
            <td><strong>Valor ($)</strong></td>
            <td><strong>A&ccedil;&otilde;es</strong></td>
        </tr>
    </thead>
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td>
            <?php 
            $objHotel = new Model_Hotel();
            $hotel = $objHotel->find($entity['hotel_id']);
            echo $hotel['nome'];
            ?>
        </td>
        <td>
            <?php 
            $objCliente = new Model_TipoCliente();
            $tipoCliente = $objCliente->find($entity['tipo_cliente_id']);
            echo $tipoCliente['descricao'];
            ?>
        </td>
        <td>
            <?php 
            $objTipo = new Model_TipoPreco();
            $tipo = $objTipo->find($entity['tipo_id']);
            echo $tipo['descricao'];
            ?>
        </td>
        <td>
            <?php echo number_format($entity['valor'], 2); ?>
        </td>
        <td>
            <a class="icon-pencil" href="<?php echo $this->url(array('controller'=>'precos','action'=>'edit','id'=>$entity['id'])); ?>" title="Editar"></a>
            <a class="icon-trash" href="<?php echo $this->url(array('controller'=>'precos','action'=>'delete','id'=>$entity['id'])); ?>" title="Excluir"></a>
        </td>
    </tr>

    <?php endforeach; ?>
</table>